<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="NoSQLSchema" nsURI="http://www.modelum.es/NoSQLSchema" nsPrefix="NoSQLSchema">
  <eClassifiers xsi:type="ecore:EClass" name="NoSQLSchema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//EntityClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refClasses" upperBound="-1"
        eType="#//ReferenceClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityClass" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralVariation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variationId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        upperBound="-1" eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstTimestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastTimestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PList" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" abstract="true" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refsTo" lowerBound="1"
        eType="#//EntityClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//StructuralVariation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregate" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregates" unique="false"
        lowerBound="1" upperBound="-1" eType="#//StructuralVariation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Null" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceClass" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="-1"
        eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variations" lowerBound="1"
        upperBound="-1" eType="#//StructuralVariation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PMap" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyType" eType="#//PrimitiveType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSet" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PTuple" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
