input:
  model: ../es.um.nosql.examples/stackoverflow/stackoverflow.xmi
  debug: true
  splits: 1

entities:
  variations:
    minInstances: 1500
    maxInstances: 1500
  includeType: true
#  dateFormat: "dd-MM-yyyy HH:mm:ss" 
#  timestamp: 17-6-1988 13:05:11
#  interval: 2000 seconds
#  randomIntervalProbability: 0
#  randomIntervalMargin: 1

attributes:
  primitiveTypes:
    strangeTypesProbability: 0
    nullProbability: 0
    stringType: word
    stringNamesFile: config/names.txt
    stringSurnamesFile: config/surnames.txt
    stringWordsFile: config/words.txt
    minIntegerAllowed: 0
    maxIntegerAllowed: 1000
    minDoubleAllowed: 0.0
    maxDoubleAllowed: 1000.0
    doubleDecimalsAllowed: 2
  tuples:
    minTupleElements: 1
    maxTupleElements: 1
    strangeTypesProbability: 0
    nullProbability: 0

associations:
  references:
    minReferenceAllowed: 2
    maxReferenceAllowed: 3
    strangeTypesProbability: 0
  aggregates:
    minAggregateAllowed: 2
    maxAggregateAllowed: 3

output:
  #database: localhost
  #databaseCollection: generated_collection
  folder: ../es.um.nosql.examples/stackoverflow/stackoverflow/json/
  #console: false

# Generate images?
# Introduce a timeout between operations and between insertions in database