input:
  model: ../es.um.nosql.models/products/products.xmi
  debug: false
  splits: 1

entities:
  variations:
    minInstances: 1000
    maxInstances: 1000
  includeType: true
#  dateFormat: "dd-MM-yyyy HH:mm:ss" 
#  timestamp: 17-6-1988 13:05:11
#  interval: 2000 seconds
#  randomIntervalProbability: 0
#  randomIntervalMargin: 1

attributes:
  primitiveTypes:
    strangeTypesProbability: 0
    nullProbability: 0
    stringType: word
    stringNamesFile: config/names.txt
    stringSurnamesFile: config/surnames.txt
    stringWordsFile: config/words.txt
    minIntegerAllowed: 0
    maxIntegerAllowed: 100
    minDoubleAllowed: 0.0
    maxDoubleAllowed: 1000.0
    doubleDecimalsAllowed: 2
  tuples:
    minTupleElements: 1
    maxTupleElements: 1
    strangeTypesProbability: 0
    nullProbability: 0

associations:
  references:
    minReferenceAllowed: 1
    maxReferenceAllowed: 2
    strangeTypesProbability: 0
  aggregates:
    minAggregateAllowed: 1
    maxAggregateAllowed: 2

output:
  database: localhost
  databaseCollection: generated_collection
  #folder: ../es.um.nosql.models/products/json/
  #console: false

# Generate images?
# Introduce a timeout between operations and between insertions in database