/*
 * generated by Xtext 2.10.0
 */
package es.um.nosql.schemainference.dslparameter.tests

import com.google.inject.Inject
import es.um.nosql.schemainference.dsl4mongoose.MongooseModel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ODMParameterInjectorProvider)
class ODMParameterParsingTest{

	@Inject
	ParseHelper<MongooseModel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
