/*
 * generated by Xtext 2.16.0
 */
package es.um.unosql.xtext.athena


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AthenaStandaloneSetup extends AthenaStandaloneSetupGenerated
{
  def static void doSetup()
  {
    new AthenaStandaloneSetup().createInjectorAndDoEMFRegistration()
  }
}
