/**
 *
 * $Id$
 */
package Variation_Diff.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Variation_Diff.AggregateType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AggregateTypeValidator
{
  boolean validate();

  boolean validateType(EList<String> value);
}
