/**
 *
 * $Id$
 */
package Variation_Diff.validation;

import Variation_Diff.FieldType;

/**
 * A sample validator interface for {@link Variation_Diff.TypeHint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypeHintValidator
{
  boolean validate();

  boolean validateWithName(String value);
  boolean validateWithType(FieldType value);
}
