/*
 * generated by Xtext 2.20.0
 */
package es.um.unosql.xtext.orion.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class OrionValidator extends AbstractOrionValidator {}
