/*
 * generated by Xtext 2.10.0
 */
package es.um.nosql.schemainference.dslparameter.ui.tests;

import com.google.inject.Injector;
import es.um.nosql.schemainference.dslparameter.ui.internal.DslparameterActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ODMParameterUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslparameterActivator.getInstance().getInjector("es.um.nosql.schemainference.dslparameter.ODMParameter");
	}

}
