input:
  model: ../es.um.nosql.examples/mongomovies.xmi

attributes:
  primitiveTypes:
    strangeTypesProbability: 0
    nullProbability: 0
    stringType: word
    minIntAllowed: 9
    maxIntAllowed: 9
    minDoubleAllowed: 3
    maxDoubleAllowed: 3.0000001
    doubleDecimalsAllowed: 0
    stringNamesFile: config/names.txt
    stringSurnamesFile: config/surnames.txt
    stringWordsFile: config/words.txt
  tuples:
    minTupleElements: 1
    maxTupleElements: 1
    strangeTypesProbability: 0
    nullProbability: 0

configure:
  minInstancesVersion: 1
  maxInstancesVersion: 1
  includeType: false

output:
  file: output/output.json
  console: true
  database: localhost


# Generate images?