input:
  model: source/oneofeach.xmi
  debug: true
  splits: 1

entities:
  versions:
    minInstances: 2
    maxInstances: 2
  includeType: true
  dateFormat: dd/MM/yyyy
  timestamp: 17/6/1988

attributes:
  primitiveTypes:
    strangeTypesProbability: 0
    nullProbability: 0
    stringType: word
    stringNamesFile: config/names.txt
    stringSurnamesFile: config/surnames.txt
    stringWordsFile: config/words.txt
    minIntegerAllowed: 0
    maxIntegerAllowed: 1000
    minDoubleAllowed: 0.0
    maxDoubleAllowed: 1000.0
    doubleDecimalsAllowed: 2
  tuples:
    minTupleElements: 1
    maxTupleElements: 1
    strangeTypesProbability: 0
    nullProbability: 0

associations:
  references:
    minReferenceAllowed: 2
    maxReferenceAllowed: 3
    strangeTypesProbability: 0
  aggregates:
    minAggregateAllowed: 2
    maxAggregateAllowed: 3

output:
#  database: localhost
#  databaseCollection: generated_collection
#  folder: output
  console: true

# Generate images?
# Introduce a timeout between operations and between insertions in database