input:
  model: ../es.um.nosql.examples/mongomovies.xmi

entities:
  versions:
    minInstances: 1
    maxInstances: 1
  includeType: false

attributes:
  primitiveTypes:
    strangeTypesProbability: 0
    nullProbability: 0
    stringType: word
    minIntAllowed: 9
    maxIntAllowed: 9
    minDoubleAllowed: 3
    maxDoubleAllowed: 3.0000001
    doubleDecimalsAllowed: 0
    stringNamesFile: config/names.txt
    stringSurnamesFile: config/surnames.txt
    stringWordsFile: config/words.txt
  tuples:
    minTupleElements: 1
    maxTupleElements: 1
    strangeTypesProbability: 0
    nullProbability: 0

associations:
  references:
    minReferenceAllowed: 0
    maxReferenceAllowed: 3
    strangeTypesProbability: 0
  aggregates:
    minAggregateAllowed: 2
    maxAggregateAllowed: 3

output:
  file: output/output.json
  console: true
  database: localhost


# Generate images?
# Introduce a timeout between operations and between insertions in database