input:
  model: source/stackoverflow.xmi
  debug: true
  splits: 100

entities:
  versions:
    minInstances: 50000
    maxInstances: 50000
  includeType: true
  dateFormat: dd/MM/yyyy
  timestamp: 17/6/1988

attributes:
  primitiveTypes:
    strangeTypesProbability: 0
    nullProbability: 0
    stringType: word
    stringNamesFile: config/names.txt
    stringSurnamesFile: config/surnames.txt
    stringWordsFile: config/words.txt
  tuples:
    minTupleElements: 1
    maxTupleElements: 1
    strangeTypesProbability: 0
    nullProbability: 0

associations:
  references:
    minReferenceAllowed: 2
    maxReferenceAllowed: 3
    strangeTypesProbability: 0
  aggregates:
    minAggregateAllowed: 2
    maxAggregateAllowed: 3

output:
  database: localhost

# Generate images?
# Introduce a timeout between operations and between insertions in database