/**
 *
 * $Id$
 */
package es.um.nosql.s13e.NoSQLSchema.validation;

import es.um.nosql.s13e.NoSQLSchema.EntityVariation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link es.um.nosql.s13e.NoSQLSchema.Aggregate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AggregateValidator
{
  boolean validate();

  boolean validateRefTo(EList<EntityVariation> value);
}
