/**
 *
 * $Id$
 */
package es.um.nosql.s13e.NoSQLSchema.validation;

import org.eclipse.emf.common.util.EList;

import es.um.nosql.s13e.NoSQLSchema.Entity;
import es.um.nosql.s13e.NoSQLSchema.EntityVariation;

/**
 * A sample validator interface for {@link es.um.nosql.s13e.NoSQLSchema.Entity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntityValidator
{
  boolean validate();

  boolean validateName(String value);
  boolean validateEntityvariations(EList<EntityVariation> value);
  boolean validateParents(EList<Entity> value);
}
