/*
 * generated by Xtext 2.16.0
 */
package es.um.nosql.s13e.xtext.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class NoSQLSchemaOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
