/**
 *
 * $Id$
 */
package es.um.nosql.s13e.DecisionTree.validation;

import org.eclipse.emf.common.util.EList;

import es.um.nosql.s13e.DecisionTree.DecisionTreeForEntity;

/**
 * A sample validator interface for {@link es.um.nosql.s13e.DecisionTree.DecisionTrees}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DecisionTreesValidator
{
  boolean validate();

  boolean validateTrees(EList<DecisionTreeForEntity> value);
  boolean validateName(String value);
}
