/**
 *
 * $Id$
 */
package es.um.nosql.s13e.DecisionTree.validation;

import es.um.nosql.s13e.DecisionTree.PropertySpec2;

/**
 * A sample validator interface for {@link es.um.nosql.s13e.DecisionTree.IntermediateNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IntermediateNodeValidator
{
  boolean validate();

  boolean validateCheckedProperty(PropertySpec2 value);
}
