/*
 * generated by Xtext 2.10.0
 */
package es.um.nosql.schemainference.dslparameter


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ODMParameterRuntimeModule extends AbstractODMParameterRuntimeModule {
}
