<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EntityDifferentiation" nsURI="http://www.modelum.es/EntityDifferentiation"
    nsPrefix="EntityDifferentiation">
  <eClassifiers xsi:type="ecore:EClass" name="EntityDifferentiation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityDiffs" upperBound="-1"
        eType="#//EntityDiff" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="ecore:EClass ../../es.um.nosql.s13e/model/nosqlschema.ecore#//NoSQLSchema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityDiff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="ecore:EClass ../../es.um.nosql.s13e/model/nosqlschema.ecore#//EntityClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationDiffs" upperBound="-1"
        eType="#//StructuralVariationDiff" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commonProps" upperBound="-1"
        eType="#//PropertySpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertySpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="ecore:EClass ../../es.um.nosql.s13e/model/nosqlschema.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needsTypeCheck" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralVariationDiff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertySpecs" upperBound="-1"
        eType="#//PropertySpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variation" lowerBound="1"
        eType="ecore:EClass ../../es.um.nosql.s13e/model/nosqlschema.ecore#//StructuralVariation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notProps" upperBound="-1"
        eType="#//PropertySpec" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
