<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="entitydifferentiation" nsURI="http://www.modelum.es/entitydifferentiation"
    nsPrefix="entitydifferentiation">
  <eClassifiers xsi:type="ecore:EClass" name="EntityDifferentiation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityDiffSpecs" upperBound="-1"
        eType="#//EntityDiffSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="ecore:EClass ../../es.um.nosql.schemainference/model/nosqlschema.ecore#//NoSQLSchema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityDiffSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="ecore:EClass ../../es.um.nosql.schemainference/model/nosqlschema.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityVersionProps" upperBound="-1"
        eType="#//EntityVersionProp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commonProps" upperBound="-1"
        eType="#//PropertySpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertySpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="ecore:EClass ../../es.um.nosql.schemainference/model/nosqlschema.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needsTypeCheck" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityVersionProp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertySpecs" upperBound="-1"
        eType="#//PropertySpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityVersion" lowerBound="1"
        eType="ecore:EClass ../../es.um.nosql.schemainference/model/nosqlschema.ecore#//EntityVersion"/>
  </eClassifiers>
</ecore:EPackage>
