/*
 * generated by Xtext 2.10.0
 */
package es.um.nosql.schemainference.dslparameter.ui;

import com.google.inject.Injector;
import es.um.nosql.schemainference.dslparameter.ui.internal.DslparameterActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ODMParameterExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DslparameterActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DslparameterActivator.getInstance().getInjector(DslparameterActivator.ES_UM_NOSQL_SCHEMAINFERENCE_DSLPARAMETER_ODMPARAMETER);
	}
	
}
