package es.um.unosql.xtext.orion.m2m;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.file.Path;

import org.junit.jupiter.api.Test;

import es.um.unosql.xtext.athena.athena.AthenaSchema;
import es.um.unosql.xtext.athena.utils.io.AthenaIO;
import es.um.unosql.xtext.orion.orion.OrionOperations;
import es.um.unosql.xtext.orion.utils.io.OrionIO;

class AggregateOpTest
{
  private Path testPath_1 = Path.of("models/tests/aggregate_ops/ImportAggregate_Ops.orion");
  private Path testPath_2 = Path.of("models/tests/aggregate_ops/ScriptAggregate_Ops.orion");
  private OrionIO orionIO          = new OrionIO();
  private AthenaIO athenaIO        = new AthenaIO();

  @Test
  void testAggregateOperations_Import()
  {
    OrionOperations orion = orionIO.load(testPath_1);
    AthenaSchema schema = new Orion2Athena().m2m(orion, false).get(0);

    assertEquals("Schema AggregateSchema:2\r\n"
        + "\r\n"
        + "entity AggregateDummy\r\n"
        + "{\r\n"
        + "  attr1,\r\n"
        + "  attr2,\r\n"
        + "  attr3\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityAddAggr1\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  aggr1: aggr<AggregateDummy_1>&,\r\n"
        + "  aggr2: aggr<AggregateDummy_2>+\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityAddAggr2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier,\r\n"
        + "    aggr1: aggr<AggregateDummy_1>&,\r\n"
        + "    aggr2: aggr<AggregateDummy_2>+\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attr1\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attr2\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityAddAggr3\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attr1,\r\n"
        + "    aggr1: aggr<AggregateDummy_1>&\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attr2,\r\n"
        + "    aggr2: aggr<AggregateDummy_2>+\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityMultAggr1\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  aggr1: aggr<AggregateDummy>&,\r\n"
        + "  aggr2: aggr<AggregateDummy>&\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityMultAggr2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier,\r\n"
        + "    aggr1: aggr<AggregateDummy>&\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    aggr2: aggr<AggregateDummy>&\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    aggr3: aggr<AggregateDummy>+\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityMultAggr3\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    aggr1: aggr<AggregateDummy>&,\r\n"
        + "    attr1\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    aggr1: aggr<AggregateDummy>&\r\n"
        + "  }\r\n"
        + "  variation 3\r\n"
        + "  {\r\n"
        + "    attr3\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityAggr1\r\n"
        + "{\r\n"
        + "  attr1,\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityAggr2\r\n"
        + "{\r\n"
        + "  attr1,\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityAggr3\r\n"
        + "{\r\n"
        + "  attr1,\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityAggr4\r\n"
        + "{\r\n"
        + "  attr1,\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity EntityAggr5\r\n"
        + "{\r\n"
        + "  attr1\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityMorphAggr1\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  refEntity1: ref<EntityAggr1 as Identifier>&\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityMorphAggr2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier,\r\n"
        + "    aggr1: aggr<AggregateDummy>&\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    refEntity2: ref<EntityAggr2 as Identifier>&\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    refEntity3: ref<EntityAggr3 as Identifier>+\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityMorphAggr3\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    refEntity4: ref<EntityAggr4 as Identifier>&,\r\n"
        + "    attr1\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    aggr4: aggr<EntityAggr4>&\r\n"
        + "  }\r\n"
        + "  variation 3\r\n"
        + "  {\r\n"
        + "    attr3\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity AggregateDummy_1\r\n"
        + "{\r\n"
        + "  aggrAttr1,\r\n"
        + "  aggrAttr2\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity AggregateDummy_2\r\n"
        + "{\r\n"
        + "  aggrAttr1,\r\n"
        + "  aggrAttr2\r\n"
        + "}\r\n", athenaIO.serialize(schema));
  }

  @Test
  void testAggregateOperations_Script()
  {
    OrionOperations orion = orionIO.load(testPath_2);
    AthenaSchema schema = new Orion2Athena().m2m(orion).get(0);

    assertEquals("Schema OneOfEach_Aggregates:1\r\n"
        + "\r\n"
        + "root entity EntityToAggr\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  aggrSimple: aggr<AggrSimple>&,\r\n"
        + "  aggrList: aggr<AggrList>+,\r\n"
        + "  strAggrSimpleChange: aggr<StrAggrSimpleChange>+,\r\n"
        + "  strAggrArrayChange: aggr<StrAggrArrayChange>&,\r\n"
        + "  numAggrSimpleChange: aggr<NumAggrSimpleChange>+,\r\n"
        + "  numAggrArrayChange: aggr<NumAggrArrayChange>&,\r\n"
        + "  aggrByHand1: aggr<AggrByHand1>+,\r\n"
        + "  aggrByHand2: aggr<AggrByHand2>&\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity AggrSimple\r\n"
        + "{\r\n"
        + "  attr1: String,\r\n"
        + "  attr2: Number,\r\n"
        + "  attr3: Map,\r\n"
        + "  attr4: List,\r\n"
        + "  innerAggrSimple: aggr<InnerAggrSimple>&,\r\n"
        + "  innerAggrList: aggr<InnerAggrList>+\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity AggrList\r\n"
        + "{\r\n"
        + "  attr1: String,\r\n"
        + "  attr2: Number,\r\n"
        + "  attr3: Map,\r\n"
        + "  attr4: List\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity InnerAggrSimple\r\n"
        + "{\r\n"
        + "  innerAttr1: String,\r\n"
        + "  innerAttr2: Number,\r\n"
        + "  innerAttr3: Map,\r\n"
        + "  innerAttr4: List\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity InnerAggrList\r\n"
        + "{\r\n"
        + "  innerAttr1: String,\r\n"
        + "  innerAttr2: Number,\r\n"
        + "  innerAttr3: Map,\r\n"
        + "  innerAttr4: List\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity StrAggrSimpleChange\r\n"
        + "{\r\n"
        + "  attr1: String,\r\n"
        + "  attr2\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity StrAggrArrayChange\r\n"
        + "{\r\n"
        + "  attr1: String,\r\n"
        + "  attr2\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity NumAggrSimpleChange\r\n"
        + "{\r\n"
        + "  attr1: Number,\r\n"
        + "  attr2\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity NumAggrArrayChange\r\n"
        + "{\r\n"
        + "  attr1: Number,\r\n"
        + "  attr2\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity AggrByHand1\r\n"
        + "{\r\n"
        + "  string1: String,\r\n"
        + "  nullAttrSimpleChange,\r\n"
        + "  nullAttrArrayChange: List,\r\n"
        + "  strAttrSimpleChange: String,\r\n"
        + "  strAttrArrayChange: List<String>\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity AggrByHand2\r\n"
        + "{\r\n"
        + "  string2: String,\r\n"
        + "  numAttrSimpleChange: Number,\r\n"
        + "  numAttrArrayChange: List<Number>\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityMorphAggr\r\n"
        + "{\r\n"
        + "  +id,\r\n"
        + "  refToAggr1: ref<Aggr1 as Identifier>&,\r\n"
        + "  refToAggr2: ref<Aggr2 as Identifier>&,\r\n"
        + "  refToAggr3: ref<Aggr3 as Identifier>+,\r\n"
        + "  refToAggr4: ref<Aggr4 as Identifier>+\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity Aggr1\r\n"
        + "{\r\n"
        + "  string1: String,\r\n"
        + "  string2: String,\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity Aggr2\r\n"
        + "{\r\n"
        + "  aList: List,\r\n"
        + "  aMap: Map,\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity Aggr3\r\n"
        + "{\r\n"
        + "  string5: String,\r\n"
        + "  string6: String,\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity Aggr4\r\n"
        + "{\r\n"
        + "  aSet: Set,\r\n"
        + "  aTuple: Tuple,\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n", athenaIO.serialize(schema));
  }
}
