package es.um.unosql.xtext.orion.m2m;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.file.Path;

import org.junit.jupiter.api.Test;

import es.um.unosql.xtext.athena.athena.AthenaSchema;
import es.um.unosql.xtext.athena.utils.io.AthenaIO;
import es.um.unosql.xtext.orion.orion.OrionOperations;
import es.um.unosql.xtext.orion.utils.io.OrionIO;

class FeatureOpTest
{
  private Path testPath_1 = Path.of("models/tests/feature_ops/ImportFeature_Ops.orion");
  private Path testPath_2 = Path.of("models/tests/feature_ops/ScriptFeature_Ops.orion");
  private OrionIO orionIO        = new OrionIO();
  private AthenaIO athenaIO      = new AthenaIO();

  @Test
  void testFeatureOperations_Import()
  {
    OrionOperations orion = orionIO.load(testPath_1);
    AthenaSchema schema = new Orion2Athena().m2m(orion, false).get(0);

    assertEquals("Schema FeatureSchema:2\r\n"
        + "\r\n"
        + "root entity EntityDelFeature_1\r\n"
        + "{\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityDelFeature_2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attrNotToDel\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attrToDelBool: Boolean\r\n"
        + "  }\r\n"
        + "  variation 3\r\n"
        + "  {\r\n"
        + "    attrToDelDouble: Double\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityRenameFeature_1\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  attrRename,\r\n"
        + "  attrRenamed_2,\r\n"
        + "  attrRenamed,\r\n"
        + "  attrNotToRenamed\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityRenameFeature_2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier,\r\n"
        + "    attrRenamed\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attrRenamed_1,\r\n"
        + "    attrNotToRen\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attrToRenBool_1: Boolean,\r\n"
        + "    attrToRen_1\r\n"
        + "  }\r\n"
        + "  variation 3\r\n"
        + "  {\r\n"
        + "    attrToRenBool_1: Boolean,\r\n"
        + "    attrToRenDouble: Double\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToCopySource_11\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  valToCopy1: String,\r\n"
        + "  valToCopy2: List,\r\n"
        + "  valToCopy3: Map\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToCopySource_12\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  valToCopy4: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToCopyTarget_1\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  thisRef: ref<EntityToCopySource_11 as Identifier>&,\r\n"
        + "  thatRef: ref<EntityToCopySource_12 as Identifier>&,\r\n"
        + "  copy1: String,\r\n"
        + "  copy2: List,\r\n"
        + "  copy3: Map,\r\n"
        + "  valToCopy4: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToCopySource_21\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier,\r\n"
        + "    attr1\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attr2\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attr3\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToCopySource_22\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier,\r\n"
        + "    attr4\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attr5\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attr6\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToCopyTarget_2\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  thisRef: ref<EntityToCopySource_21 as Identifier>&,\r\n"
        + "  thatRef: ref<EntityToCopySource_22 as Identifier>&,\r\n"
        + "  copy1,\r\n"
        + "  ?copy2,\r\n"
        + "  ?copy3,\r\n"
        + "  valToCopy4\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToMoveSource_11\r\n"
        + "{\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToMoveSource_12\r\n"
        + "{\r\n"
        + "  +id: Identifier\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToMoveTarget_1\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  thisRef: ref<EntityToMoveSource_11 as Identifier>&,\r\n"
        + "  thatRef: ref<EntityToMoveSource_12 as Identifier>&,\r\n"
        + "  move1: String,\r\n"
        + "  move2: List,\r\n"
        + "  move3: Map,\r\n"
        + "  valToMove4: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToMoveSource_21\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attrN\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attrN\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToMoveSource_22\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    attr5,\r\n"
        + "    attrN\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    attr6,\r\n"
        + "    attrN\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToMoveTarget_2\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  thisRef: ref<EntityToMoveSource_21 as Identifier>&,\r\n"
        + "  thatRef: ref<EntityToMoveSource_22 as Identifier>&,\r\n"
        + "  move1,\r\n"
        + "  ?move2,\r\n"
        + "  ?move3,\r\n"
        + "  valToMove4\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToNest_1\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  name,\r\n"
        + "  age,\r\n"
        + "  aList,\r\n"
        + "  aMap,\r\n"
        + "  nestedAggr_1: aggr<NestedAggr_1>&\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToNest_2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier,\r\n"
        + "    nestedAggr_2: aggr<NestedAggr_2>&\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    street,\r\n"
        + "    postalCode\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    aList,\r\n"
        + "    aMap\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity MyNest_1\r\n"
        + "{\r\n"
        + "  nest2\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity MyNest_2\r\n"
        + "{\r\n"
        + "  nest3\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity MyNest_3\r\n"
        + "{\r\n"
        + "  nest6\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToUnnest_1\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  nest: aggr<MyNest_1>&,\r\n"
        + "  nest1,\r\n"
        + "  nest3\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToUnnest_2\r\n"
        + "{\r\n"
        + "  common\r\n"
        + "  {\r\n"
        + "    +id: Identifier,\r\n"
        + "    nest1,\r\n"
        + "    nest2,\r\n"
        + "    nest4,\r\n"
        + "    nest5\r\n"
        + "  }\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    nest_2: aggr<MyNest_2>&\r\n"
        + "  }\r\n"
        + "  variation 2\r\n"
        + "  {\r\n"
        + "    nest_3: aggr<MyNest_3>&\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity Nest\r\n"
        + "{\r\n"
        + "  variation 1\r\n"
        + "  {\r\n"
        + "    nest1,\r\n"
        + "    nest2\r\n"
        + "  }\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity NestedAggr_1\r\n"
        + "{\r\n"
        + "  street,\r\n"
        + "  postalCode,\r\n"
        + "  city,\r\n"
        + "  nest: aggr<Nest.1>&\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity NestedAggr_2\r\n"
        + "{\r\n"
        + "  name,\r\n"
        + "  nest: aggr<Nest.1>&,\r\n"
        + "  ?age,\r\n"
        + "  ?city\r\n"
        + "}\r\n", athenaIO.serialize(schema));
  }

  @Test
  void testFeatureOperations_Script()
  {
    OrionOperations orion = orionIO.load(testPath_2);
    AthenaSchema schema = new Orion2Athena().m2m(orion).get(0);

    assertEquals("Schema ScriptFeature_Ops:1\r\n"
        + "\r\n"
        + "root entity EntityToRemove\r\n"
        + "{\r\n"
        + "  +id: Identifier,\r\n"
        + "  +attrTrue1,\r\n"
        + "  +attrTrue2: String,\r\n"
        + "  +attrTrue3: Number,\r\n"
        + "  +attrTrue4: Double,\r\n"
        + "  +attrTrue5: Boolean\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToCopySource1\r\n"
        + "{\r\n"
        + "  +id: String,\r\n"
        + "  valueToCopy1: String,\r\n"
        + "  valueToCopy2: List,\r\n"
        + "  valueToCopy3: Map\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToCopySource2\r\n"
        + "{\r\n"
        + "  +id: String,\r\n"
        + "  valueToCopy4: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToCopyTarget\r\n"
        + "{\r\n"
        + "  +id: String,\r\n"
        + "  thisRef: String,\r\n"
        + "  thatRef: String,\r\n"
        + "  copy1: String,\r\n"
        + "  copy2: List,\r\n"
        + "  copy3: Map,\r\n"
        + "  valueToCopy4: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToMoveSource1\r\n"
        + "{\r\n"
        + "  +id: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToMoveSource2\r\n"
        + "{\r\n"
        + "  +id: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToMoveTarget\r\n"
        + "{\r\n"
        + "  +id: String,\r\n"
        + "  thisRef: String,\r\n"
        + "  thatRef: String,\r\n"
        + "  move1: String,\r\n"
        + "  move2: List,\r\n"
        + "  move3: Map,\r\n"
        + "  move4: String\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToNest\r\n"
        + "{\r\n"
        + "  +id: String,\r\n"
        + "  name,\r\n"
        + "  age,\r\n"
        + "  aList: List,\r\n"
        + "  aMap: Map,\r\n"
        + "  nestedAggr: aggr<NestedAggr>&\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity NestAggrNest1\r\n"
        + "{\r\n"
        + "  nest1,\r\n"
        + "  nest2,\r\n"
        + "  nest3\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity NestAggrNest2\r\n"
        + "{\r\n"
        + "  nest4,\r\n"
        + "  nest5,\r\n"
        + "  nest6\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity NestedAggr\r\n"
        + "{\r\n"
        + "  street,\r\n"
        + "  postalCode,\r\n"
        + "  city,\r\n"
        + "  nestAggrNest1: aggr<NestAggrNest1>&,\r\n"
        + "  nestAggrNest2: aggr<NestAggrNest2>+\r\n"
        + "}\r\n"
        + "\r\n"
        + "root entity EntityToUnnest\r\n"
        + "{\r\n"
        + "  +id: String,\r\n"
        + "  name,\r\n"
        + "  age,\r\n"
        + "  unnestAggrNest1: aggr<UnnestAggrNest1>&,\r\n"
        + "  unnestAggrNest2: aggr<UnnestAggrNest2>&,\r\n"
        + "  street,\r\n"
        + "  postalCode,\r\n"
        + "  city,\r\n"
        + "  aList: List,\r\n"
        + "  aMap: Map,\r\n"
        + "  nest4\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity UnnestAggrNest1\r\n"
        + "{\r\n"
        + "  nest1,\r\n"
        + "  nest2,\r\n"
        + "  nest3\r\n"
        + "}\r\n"
        + "\r\n"
        + "entity UnnestAggrNest2\r\n"
        + "{\r\n"
        + "  nest5,\r\n"
        + "  nest6\r\n"
        + "}\r\n", athenaIO.serialize(schema));
  }
}
