/*
 * generated by Xtext 2.16.0
 */
package es.um.nosql.s13e.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NoSQLSchemaRuntimeModule extends AbstractNoSQLSchemaRuntimeModule {
}
