/*
 * generated by Xtext 2.14.0
 */
package es.um.unosql.xtext.skiql

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SkiQLStandaloneSetup extends SkiQLStandaloneSetupGenerated {

	def static void doSetup() {
		new SkiQLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
