/*
 * generated by Xtext 2.14.0
 */
package es.um.unosql.xtext.skiql

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SkiQLRuntimeModule extends AbstractSkiQLRuntimeModule {
}
