/*
 * generated by Xtext 2.23.0
 */
package es.um.unosql.xtext.skiql.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class SkiQLUiModule extends AbstractSkiQLUiModule {
}
