/*
 * generated by Xtext 2.10.0
 */
package es.um.nosql.schemainference.dslparameter


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ODMParameterStandaloneSetup extends ODMParameterStandaloneSetupGenerated {

	def static void doSetup() {
		new ODMParameterStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
