/*
 * generated by Xtext 2.10.0
 */
package es.um.nosql.schemainference.dslparameter.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class ODMParameterOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
