/*
 * generated by Xtext 2.10.0
 */
package es.um.nosql.schemainference.dslparameter.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractODMParameterScopeProvider extends DelegatingScopeProvider {
}
