/*
 * generated by Xtext 2.25.0
 */
package es.um.unosql.xtext.orion


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OrionStandaloneSetup extends OrionStandaloneSetupGenerated {

	def static void doSetup() {
		new OrionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
