mapper: Morphia
entities:
  - name: Album
    indexes:
      - attr: [name, releaseYear]
        type: [asc, desc]
        unique: true
        sparse: true
        sparse: true
        background: false

    validators:
      - attr: releaseYear
        min: 1900
        max: 2019
      - attr: name
        maxLength: 300
        message: This album's name is too long

  - name: Review
    validators:
      - attr: rank
        enumValues: [Excelent, Very good, Good, Poor, Terrible]
      - attr: stars
        min: 0
        max: 5