mapper: Morphia
entities:
  - name: Persons
    indexes:
      - attr: ['name']
        type: [asc]
        unique: true
        background: false
      - attr: ['surname']
        type: [desc]
        name: "Custom NombreIndice"
        disableValidation: false
    validators:
      - attr: name
        match: "/name[0-4]/"
        minLength: 2
        maxLength: 4
      - attr: surname
        custom: "{validator: function(v) { return /surname[0-9]/.test(v);}, message: \"error\"}"
