mapper: Morphia
entities:
  - name: Movie
    validators:
      - attr: genre
        type: enum
        value: ['drama', 'comedy', 'children']
      - attr: title
        type:  comparison
        value: ['length < 40']
    uniques: ['title']
    updates: ['genre', 'title']
    indexes:
      - attr: ['_id']
        type: Hashed
      - attr: ['year']
        type: text
  - name: Director
    uniques: ['name']
    updates: ['name']
    indexes:
      - attr: ['_id']
        type: Hashed
      - attr: ['name']
        type: text
  - name: Criticism
    validators:
      - attr: color
        type: enum
        value: ['green', 'red', 'yellow']
    uniques: ['journalist']
discriminator: Movietheater