mapper: Morphia
entities:
  - name: Persons
    validators:
      - attr: age
        min: 0
        max: 60
      - attr: status
        minLength: 3
      - attr: surname
        maxLength: 10
      - attr: name
        minLength: 3
        maxLength: 10