mapper: Morphia
Entity: Movie
  - validators:
    - genre:
      - enum: ['drama', 'comedy', 'children']
    - title:
      - comparison: ['length < 40']
  - uniques: ['title']
  - updates: ['genre', 'title']
  - indexes:
    - _id: kind:Hash
    - year: kind:Sorted
Entity: Director
  - uniques: ['name']
  - updates: ['name']
  - indexes:
    - _id: kind:Hash
    - year: kind:Sorted
Entity: Criticism
  - validators:
    - color:
      - enum: ['green', 'red', 'yellow']
  - uniques: ['journalist']
discriminator: Entity MovieTheater