/*
 * generated by Xtext 2.14.0
 */
package es.um.nosql.s13e.xtext.ide


/**
 * Use this class to register ide components.
 */
class NoSQLSchemaIdeModule extends AbstractNoSQLSchemaIdeModule {
}
