/**
 *
 * $Id$
 */
package es.um.nosql.s13e.EntityDifferentiation.validation;

import es.um.nosql.s13e.NoSQLSchema.NoSQLSchema;
import es.um.nosql.s13e.EntityDifferentiation.EntityDiffSpec;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link es.um.nosql.s13e.EntityDifferentiation.EntityDifferentiation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntityDifferentiationValidator
{
  boolean validate();

  boolean validateEntityDiffSpecs(EList<EntityDiffSpec> value);
  boolean validateName(String value);
  boolean validateSchema(NoSQLSchema value);
}
