/*
 * generated by Xtext 2.10.0
 */
package es.um.nosql.schemainference.dslparameter.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ODMParameterAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("es/um/nosql/schemainference/dslparameter/parser/antlr/internal/InternalODMParameter.tokens");
	}
}
